### ISSUE TITLE
Try-error forwarding by ensure()

### ISSUE THREAD

**Issue by williFiebranz** [smbache/ensurer#13]
Hello,

I wonder if try-errors could be forwarded in the same desirable way as normal errors are handled by the ensure() function:

>require(ensurer)
>require(magrittr)  
>stop("I want to see this error.") %>%
>    ensure(is.character, fail_with = stop("I don't want to see this error")  
>try({stop("I want to see this error.")}) %>%
>    ensure(is.character, fail_with = stop("I don't want to see this error"))

**Comment by smbache** [comment]
Not sure exactly what you want. But, first notice that `fail_with` takes a *value* or a *function*, and so it makes little sense to provide `stop(...)` itself. Also, `is.character(try(stop("message")))` is `TRUE`, and so in your second example the test actually passes, but the error (you don't want to see) is still raised (because it is not wrapped in a function) Could you expand on the issue/question if this`information doesn't help?

**Comment by williFiebranz** [comment]
Thanks for your reply.

Never mind, I assumed that the error thrown by the stop() expression gets passed through the pipe and remains unchanged, regardless of the arguments of the following ensure expressions. That is of course nonsense. Instead the whole expression aborts and the error gets printed.

Sorry for the bother.

**Comment by smbache** [comment]
Never mind. Always let me know if something is unclear or unreasonable.
